import type { Metadata } from "next";
import Header from "@/components/blocks/Header";
import Footer from "@/components/blocks/Footer";
import { draftMode } from "next/headers";
import { SanityLive } from "@/sanity/lib/live";
import { handleError } from "@/sanity/lib/client-utils";
import { DisableDraftMode } from "@/components/sanity/DisableDraftMode";
import { VisualEditing } from "next-sanity";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {(await draftMode()).isEnabled && (
        <>
          {/* <DisableDraftMode /> */}
          <DisableDraftMode />
          {/*  Enable Visual Editing, only to be rendered when Draft Mode is enabled */}
          <VisualEditing />
        </>
      )}
      <SanityLive onError={handleError} />

      <div className="grid min-h-[100dvh] grid-rows-[auto_1fr_auto]">
        <Header />
        <main>{children}</main>
        <Footer />
      </div>
    </>
  );
}
